version: '3.9'
services:
  db:
    image: mysql:8
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 20012003
      MYSQL_DATABASE: storecrud
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
  app:
    build: .
    container_name: my-spring-app-container
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/storecrud
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 20012003
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
